package com.ramitsuri.choresclient.resources

enum class LocalizedString {
    FILTER_ALL,
    ON_COMPLETION,
    PERSON_FILTER,
    HOUSE_FILTER,
    SETTINGS,
    REPEAT_UNIT_NONE,
    REPEAT_UNIT_DAY,
    REPEAT_UNIT_WEEK,
    REPEAT_UNIT_MONTH,
    REPEAT_UNIT_HOUR,
    REPEAT_UNIT_YEAR,
    REPEAT_UNIT_ON_COMPLETE,
    TODAY,
    TOMORROW,
    YESTERDAY,
    NOTIFICATION_ACTION_SNOOZE_HOUR,
    NOTIFICATION_ACTION_SNOOZE_DAY,
    NOTIFICATION_ACTION_COMPLETE,
    NOTIFICATION_ACTION_WONT_DO
}