name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test
